# Generated by Django 4.2.2 on 2023-06-29 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_employees_orderemployee'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='orders',
            field=models.ManyToManyField(through='orders.OrderEmployee', to='orders.order'),
        ),
    ]
