# Generated by Django 4.2.2 on 2023-06-29 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
