# Generated by Django 4.2.2 on 2023-06-29 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_income_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='expenses',
        ),
        migrations.RemoveField(
            model_name='product',
            name='incomes',
        ),
        migrations.DeleteModel(
            name='Income',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
