# Generated by Django 4.2.2 on 2023-06-29 10:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0003_remove_product_expenses_remove_product_incomes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 6, 29, 10, 45, 28, 847662, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
