# Generated by Django 4.2.2 on 2023-06-29 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0005_alter_income_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='custom_field',
            field=models.CharField(default='default_value', max_length=100),
        ),
    ]
