# Generated by Django 4.2.2 on 2023-06-29 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_employees_orderemployee'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='custom_field',
            field=models.CharField(default='default_value', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
