# Generated by Django 4.2.2 on 2023-07-03 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_employee_date'),
        ('orders', '0004_orderemployee_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='custom_field',
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(null=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_address',
            field=models.CharField(max_length=200, verbose_name='Адрес доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='employees',
            field=models.ManyToManyField(to='employees.employee', verbose_name='Сотрудник'),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='order',
            name='product_name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='orderemployee',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee', verbose_name='Сотрудник'),
        ),
        migrations.AlterField(
            model_name='orderemployee',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order', verbose_name='Название заказа'),
        ),
    ]
